# Generated by Django 3.0.7 on 2020-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('uni', models.CharField(max_length=100)),
                ('school1', models.CharField(max_length=100)),
                ('school2', models.CharField(max_length=100)),
            ],
        ),
    ]
